---
- name: Deploy Machine
  collections:
    - community.vmware
    - ansible.windows
  vars_files:
    - vms_data.json
  hosts: all
  tasks:
    - name: Deploy Windows VM from template
      community.vmware.vmware_guest:
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacentere }}"
        folder: "/{{ datacenter }}/vm/{{ vm_folder }}"
        name: "{{ item.name }}"
        template: "{{ vm_template }}"
        state: powered_on
        guest_id: rhel8_64Guest  # Change to match your OS
        hardware:
          memory_mb: 4096
          num_cpus: 2
          scsi: lsilogic
        networks:
          - name: "VM Network"
            ip: "{{ item.ip }}"
            netmask: "{{ item.subnet_mask }}"
            gateway: "{{ item.gateway }}"
            device_type: vmxnet3
            type: static
        esxi_host: "{{ esxi_host }}"
      loop: "{{ vm_list }}"
