- name:  Report all VMware VM snapshots
  collections:
    - community.vmware
    - ansible.windows
  hosts: all
  tasks:
    - name: Gather all snapshot information across the datacenter
      community.vmware.vmware_all_snapshots_info:
        validate_certs: no
        datacenter: "{{ datacenter }}"
      register: snapshot_info
